"""add content_hash to pages

Revision ID: 839fbdf623d6
Revises: 8f6f9d96a189
Create Date: 2026-04-18 12:40:48.840996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839fbdf623d6'
down_revision: Union[str, Sequence[str], None] = '8f6f9d96a189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content_hash', sa.Text(), nullable=True))
    op.create_index('idx_pages_content_hash', 'pages', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pages_content_hash', table_name='pages')
    op.drop_column('pages', 'content_hash')
    # ### end Alembic commands ###
