"""initial

Revision ID: 8f6f9d96a189
Revises: 
Create Date: 2026-04-05 18:36:10.100712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6f9d96a189'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('scheme', sa.Text(), nullable=True),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_urls_host', 'urls', ['host'], unique=False)
    op.create_index('idx_urls_is_internal', 'urls', ['is_internal'], unique=False)
    op.create_table('fetch_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.BigInteger(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fetch_attempts_attempted_at', 'fetch_attempts', ['attempted_at'], unique=False)
    op.create_index('idx_fetch_attempts_success', 'fetch_attempts', ['success'], unique=False)
    op.create_index('idx_fetch_attempts_url_id', 'fetch_attempts', ['url_id'], unique=False)
    op.create_table('frontier',
    sa.Column('url_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('discovered_from_url_id', sa.BigInteger(), nullable=True),
    sa.Column('next_fetch_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['discovered_from_url_id'], ['urls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url_id')
    )
    op.create_index('idx_frontier_priority', 'frontier', ['priority'], unique=False)
    op.create_index('idx_frontier_status_next_fetch', 'frontier', ['status', 'next_fetch_at'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('content_length', sa.BigInteger(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('is_html', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pages_fetched_at', 'pages', ['fetched_at'], unique=False)
    op.create_index('idx_pages_http_status', 'pages', ['http_status'], unique=False)
    op.create_index('idx_pages_url_id', 'pages', ['url_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_page_id', sa.Integer(), nullable=False),
    sa.Column('to_url_id', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('nofollow', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_links_from_page_id', 'links', ['from_page_id'], unique=False)
    op.create_index('idx_links_is_internal', 'links', ['is_internal'], unique=False)
    op.create_index('idx_links_to_url_id', 'links', ['to_url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_links_to_url_id', table_name='links')
    op.drop_index('idx_links_is_internal', table_name='links')
    op.drop_index('idx_links_from_page_id', table_name='links')
    op.drop_table('links')
    op.drop_index('idx_pages_url_id', table_name='pages')
    op.drop_index('idx_pages_http_status', table_name='pages')
    op.drop_index('idx_pages_fetched_at', table_name='pages')
    op.drop_table('pages')
    op.drop_index('idx_frontier_status_next_fetch', table_name='frontier')
    op.drop_index('idx_frontier_priority', table_name='frontier')
    op.drop_table('frontier')
    op.drop_index('idx_fetch_attempts_url_id', table_name='fetch_attempts')
    op.drop_index('idx_fetch_attempts_success', table_name='fetch_attempts')
    op.drop_index('idx_fetch_attempts_attempted_at', table_name='fetch_attempts')
    op.drop_table('fetch_attempts')
    op.drop_index('idx_urls_is_internal', table_name='urls')
    op.drop_index('idx_urls_host', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
